# 项目信息
site_name: Better_StarLink
site_url: https://StarLink.tjsec.cn
site_author: 探姬
site_description: 更好的可读性和视觉效果,优雅的与源项目404StarLink保持同步。

# 仓库信息
repo_name: Better_StarLink
repo_url: https://github.com/ProbiusOfficial/Better_StarLink
edit_uri: https://github.com/ProbiusOfficial/Better_StarLink/tree/main/docs/


# 自定义配置部分
theme:
  name: material
  # custom_dir: overrides
  language: zh
  features:
    # - announce.dismiss        # 通知关闭
    - content.action.edit       # 编辑操作
    - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    # - header.autohide         # 自动隐藏头部
    # - navigation.expand       # 展开导航
    - navigation.indexes        # 导航索引
    - navigation.instant      # 即时导航
    # - navigation.prune        # 导航修剪
    # - navigation.sections     # 导航节
    - navigation.tabs         # 导航标签
    # - navigation.tabs.sticky  # 固定导航标签
    - navigation.top            # 导航顶部
    - navigation.footer         # 导航底部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随
    # - toc.integrate           # 目录整合

  # 调色板配置
  palette:
  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      primary: black
      
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


  # 字体配置
  font:
    text: Noto Sans SC
    code: Fira Code

  favicon: assets/logo_star.png

  logo: assets/logo_star.png

  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

# 额外配置
extra: 
  disqus: 'open' # 评论系统

  generator: false  
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/probiusofficial
    - icon: fontawesome/brands/github
      link: https://github.com/probiusofficial
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/27109929
    - icon: fontawesome/solid/paper-plane
      link: mailto:<probiuslinx@gmail.com> 


# 插件选项
plugins:
  - search

# Markdown 扩展语法支持
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details

  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # - pymdownx.tabbed:
  #     alternate_style: true
  #     combine_header_slug: true
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  
# 页面目录
nav:
# nav start

  - 主页: 
      - index.md
      - 甲方工具: party_a.md
      - 信息收集: reconnaissance.md
      - 漏洞探测: vulnerability_assessment.md
      - 攻击与利用: penetration_test.md
      - 信息分析: information_analysis.md
      - 内网工具: intranet_tools.md
      - 其他: others.md

  - 项目目录及细节:
    - detail/index.md
    - afrog: detail/afrog.md
    - Antenna: detail/Antenna.md
    - antSword: detail/antSword.md
    - AppInfoScanner: detail/AppInfoScanner.md
    - appshark: detail/appshark.md
    - As-Exploits: detail/As-Exploits.md
    - BinAbsInspector: detail/BinAbsInspector.md
    - BurpCrypto: detail/BurpCrypto.md
    - camille: detail/camille.md
    - CDK: detail/CDK.md
    - Cloud-Bucket-Leak-Detection-Tools: detail/Cloud-Bucket-Leak-Detection-Tools.md
    - CodeReviewTools: detail/CodeReviewTools.md
    - Cola-Dnslog: detail/Cola-Dnslog.md
    - ct: detail/ct.md
    - DNSlog-GO: detail/DNSlog-GO.md
    - dperf: detail/dperf.md
    - Elkeid: detail/Elkeid.md
    - ENScanGo: detail/ENScanGo.md
    - f8x: detail/f8x.md
    - frida-skeleton: detail/frida-skeleton.md
    - fscan: detail/fscan.md
    - Glass: detail/Glass.md
    - gshark: detail/gshark.md
    - HackBrowserData: detail/HackBrowserData.md
    - Hades: detail/Hades.md
    - HaE: detail/HaE.md
    - Heimdallr: detail/Heimdallr.md
    - java-object-searcher: detail/java-object-searcher.md
    - js-cookie-monitor-debugger-hook: detail/js-cookie-monitor-debugger-hook.md
    - Juggler: detail/Juggler.md
    - JYso: detail/JYso.md
    - ksubdomain: detail/ksubdomain.md
    - KunLun-M: detail/KunLun-M.md
    - Kunpeng: detail/Kunpeng.md
    - Kunyu: detail/Kunyu.md
    - LBot: detail/LBot.md
    - linglong: detail/linglong.md
    - LSpider: detail/LSpider.md
    - MDUT: detail/MDUT.md
    - murphysec: detail/murphysec.md
    - myscan: detail/myscan.md
    - MySQL-Fake-Server: detail/MySQL-Fake-Server.md
    - MySQLMonitor: detail/MySQLMonitor.md
    - MysqlT: detail/MysqlT.md
    - OpenStar: detail/OpenStar.md
    - passive-scan-client: detail/passive-scan-client.md
    - Platypus: detail/Platypus.md
    - Pocassist: detail/Pocassist.md
    - pocsuite3: detail/pocsuite3.md
    - PortForward: detail/PortForward.md
    - rakshasa: detail/rakshasa.md
    - Redis-Rogue-Server: detail/Redis-Rogue-Server.md
    - scaninfo: detail/scaninfo.md
    - ServerScan: detail/ServerScan.md
    - shellcodeloader: detail/shellcodeloader.md
    - Stowaway: detail/Stowaway.md
    - Tai-e: detail/Tai-e.md
    - vArmor: detail/vArmor.md
    - veinmind-tools: detail/veinmind-tools.md
    - Viper: detail/Viper.md
    - wam: detail/wam.md
    - WMIHACKER: detail/WMIHACKER.md
    - ysomap: detail/ysomap.md
    - ZoomEye-go: detail/ZoomEye-go.md
    - ZoomEye-Python: detail/ZoomEye-Python.md
    - ZoomEye-Tools: detail/ZoomEye-Tools.    

  - Kcon兵器谱: 
    - column/index.md
    - Kcon2021: column/2021KCon_exhibition_with_starlink.md
    - Kcon2022: column/2022KCon_exhibition_with_starlink.md
    - Kcon2023: column/2023KCon_exhibition_with_starlink.md

  - 星际奇兵: Raiders/index.md

  # nav end

