name: Deploy to Github Pages and Update from StarLink

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest

    steps:
      # 检出当前仓库
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取完整的 git 历史, 这样可以推送更改

      # 拉取 knownsec/404StarLink 仓库到 docs 文件夹
      - name: Clone knownsec/404StarLink to docs folder
        run: |
          git clone https://github.com/knownsec/404StarLink.git docs

      # 移除 .github 文件夹
      - name: Remove .github folder from docs
        run: rm -rf docs/.github

      # 推送更改到当前仓库
      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Updated docs from knownsec/404StarLink"
          git push
   
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9

      # - name: Install dependencies
      #   run: pip install mkdocs-material

      # - name: Deploy MkDocs
      #   run: mkdocs gh-deploy --force

      
